import { StateProvider } from '@/components/StateProvider/StateProvider';
import type { Metadata } from 'next';

import '@/styles/variables.css';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'Create sNext App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StateProvider>{children}</StateProvider>
      </body>
    </html>
  );
}
